export const GET_RECIPES_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_RECIPES_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const HANDLE_ERROR = "HANDLE_ERROR";

export const SET_NEXT_PAGE = "SET_NEXT_PAGE";

export const NEXT_PAGE_LOADING = "NEXT_PAGE_LOADING";
export const NEXT_PAGE_LOADED = "NEXT_PAGE_LOADED";

export const CREATE_A_QUERY = "CREATE_A_QUERY";
export const CLEAR_THE_QUERY = "CLEAR_THE_QUERY";
export const HANDLE_LAST_QUERY = "HANDLE_LAST_QUERY";

export const CHANGE_THE_PAGE = "CHANGE_THE_PAGE";

export const SET_QUERY_PATH = "SET_QUERY_PATH";

export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_RECIPES_DATA = "GET_RECIPES_DATA";

export const HANDLE_MODAL = "HANDLE_MODAL";
export const SHOW_NEWSLETTER = "SHOW_NEWSLETTER";
export const HIDE_NEWSLETTER = "HIDE_NEWSLETTER";
export const HANDLE_MENU = "HANDLE_MENU";
export const SAVE_EMAIL = "SAVE_EMAIL";
export const SHOW_AUTH = "SHOW_AUTH";
export const HIDE_AUTH = "HIDE_AUTH";

export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";

export const CHANGE_CALORIES = "CHANGE_CALORIES";

export const CHANGE_DIET = "CHANGE_DIET";
export const CHANGE_HEALTH = "CHANGE_HEALTH";
export const CHANGE_MEAL = "CHANGE_MEAL";
export const CHANGE_CUISINE = "CHANGE_CUISINE";
export const CHANGE_DISH = "CHANGE_DISH";
export const CHANGE_MININPUT = "CHANGE_MININPUT";
export const CHANGE_MAXINPUT = "CHANGE_MAXINPUT";
