export const GET_RECIPES_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_RECIPES_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const ROTATE_STAR = "ROTATE_STAR";
export const REFRESH_STAR = "REFRESH_STAR";

export const HANDLE_ERROR = "HANDLE_ERROR";

export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const NEXT_PAGE_LOADING = "NEXT_PAGE_LOADING";
export const NEXT_PAGE_LOADED = "NEXT_PAGE_LOADED";

export const CREATE_A_QUERY = "CREATE_A_QUERY";
export const CLEAR_THE_QUERY = "CLEAR_THE_QUERY";
export const HANDLE_LAST_QUERY = "HANDLE_LAST_QUERY";

export const CHANGE_THE_PAGE = "CHANGE_THE_PAGE";

export const SET_PATH = "SET_PATH";
export const SET_QUERY_PATH = "SET_QUERY_PATH";
export const SET_LOCALSTR_PATH = "SET_LOCALSTR_PATH";
export const CHANGE_CURRENT_PATH = "CHANGE_CURRENT_PATH";

export const GET_RECIPE = "GET_RECIPE";
export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_RECIPES_DATA = "GET_RECIPES_DATA";
export const UPDATE_LOCALSTR_RECIPES = "UPDATE_LOCALSTR_RECIPES";

export const HANDLE_MODAL = "HANDLE_MODAL";
export const SAVE_EMAIL = "SAVE_EMAIL";

export const CHANGE_CALORIES = "CHANGE_CALORIES";

export const CHANGE_DIET = "CHANGE_DIET";
export const CHANGE_HEALTH = "CHANGE_HEALTH";
export const CHANGE_MEAL = "CHANGE_MEAL";
export const CHANGE_CUISINE = "CHANGE_CUISINE";
export const CHANGE_DISH = "CHANGE_DISH";
export const CHANGE_MININPUT = "CHANGE_MININPUT";
export const CHANGE_MAXINPUT = "CHANGE_MAXINPUT";
